export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SET_CONNECTION_ERROR_ALERT = 'SET_CONNECTION_ERROR_ALERT'
export const REMOVE_CONNECTION_ERROR_ALERT = 'REMOVE_CONNECTION_ERROR_ALERT'
