export const CMCA_BANK_ACCOUNT_LIST_REQUEST = 'CMCA_BANK_ACCOUNT_LIST_REQUEST'
export const CMCA_BANK_ACCOUNT_LIST_SUCCESS = 'CMCA_BANK_ACCOUNT_LIST_SUCCESS'
export const CMCA_BANK_ACCOUNT_LIST_FAIL = 'CMCA_BANK_ACCOUNT_LIST_FAIL'
export const CMCA_BANK_ACCOUNT_LIST_RESET = 'CMCA_BANK_ACCOUNT_LIST_RESET'
