export const CMCA_BANK_TYPES_2017_LIST_REQUEST =
  'CMCA_BANK_TYPES_2017_LIST_REQUEST'
export const CMCA_BANK_TYPES_2017_LIST_SUCCESS =
  'CMCA_BANK_TYPES_2017_LIST_SUCCESS'
export const CMCA_BANK_TYPES_2017_LIST_FAIL = 'CMCA_BANK_TYPES_2017_LIST_FAIL'
export const CMCA_BANK_TYPES_2017_LIST_RESET = 'CMCA_BANK_TYPES_2017_LIST_RESET'

export const CMCA_BANK_TYPES_2021_LIST_REQUEST =
  'CMCA_BANK_TYPES_2021_LIST_REQUEST'
export const CMCA_BANK_TYPES_2021_LIST_SUCCESS =
  'CMCA_BANK_TYPES_2021_LIST_SUCCESS'
export const CMCA_BANK_TYPES_2021_LIST_FAIL = 'CMCA_BANK_TYPES_2021_LIST_FAIL'
export const CMCA_BANK_TYPES_2021_LIST_RESET = 'CMCA_BANK_TYPES_2021_LIST_RESET'
