export const CMCA_REGION_POPULATION_2017_LIST_REQUEST =
  'CMCA_REGION_POPULATION_2017_LIST_REQUEST'
export const CMCA_REGION_POPULATION_2017_LIST_SUCCESS =
  'CMCA_REGION_POPULATION_2017_LIST_SUCCESS'
export const CMCA_REGION_POPULATION_2017_LIST_FAIL =
  'CMCA_REGION_POPULATION_2017_LIST_FAIL'
export const CMCA_REGION_POPULATION_2017_LIST_RESET =
  'CMCA_REGION_POPULATION_2017_LIST_RESET'

export const CMCA_REGION_POPULATION_2021_LIST_REQUEST =
  'CMCA_REGION_POPULATION_2021_LIST_REQUEST'
export const CMCA_REGION_POPULATION_2021_LIST_SUCCESS =
  'CMCA_REGION_POPULATION_2021_LIST_SUCCESS'
export const CMCA_REGION_POPULATION_2021_LIST_FAIL =
  'CMCA_REGION_POPULATION_2021_LIST_FAIL'
export const CMCA_REGION_POPULATION_2021_LIST_RESET =
  'CMCA_REGION_POPULATION_2021_LIST_RESET'
