export const CMCA_PAYMENTS_REQUEST = 'CMCA_PAYMENTS_REQUEST'
export const CMCA_PAYMENTS_SUCCESS = 'CMCA_PAYMENTS_SUCCESS'
export const CMCA_PAYMENTS_FAIL = 'CMCA_PAYMENTS_FAIL'
export const CMCA_PAYMENTS_RESET = 'CMCA_PAYMENTS_RESET'
