export const CMCA_PERSON_LIST_REQUEST = 'CMCA_PERSON_LIST_REQUEST'
export const CMCA_PERSON_LIST_SUCCESS = 'CMCA_PERSON_LIST_SUCCESS'
export const CMCA_PERSON_LIST_FAIL = 'CMCA_PERSON_LIST_FAIL'
export const CMCA_PERSON_LIST_RESET = 'CMCA_PERSON_LIST_RESET'
