export const MV_BANK_ACCOUNT_LIST_REQUEST = 'MV_BANK_ACCOUNT_LIST_REQUEST'
export const MV_BANK_ACCOUNT_LIST_SUCCESS = 'MV_BANK_ACCOUNT_LIST_SUCCESS'
export const MV_BANK_ACCOUNT_LIST_FAIL = 'MV_BANK_ACCOUNT_LIST_FAIL'
export const MV_BANK_ACCOUNT_LIST_RESET = 'MV_BANK_ACCOUNT_LIST_RESET'
