export const MV_PERSON_LIST_REQUEST = 'MV_PERSON_LIST_REQUEST'
export const MV_PERSON_LIST_SUCCESS = 'MV_PERSON_LIST_SUCCESS'
export const MV_PERSON_LIST_FAIL = 'MV_PERSON_LIST_FAIL'
export const MV_PERSON_LIST_RESET = 'MV_PERSON_LIST_RESET'
