export const SML_LEASE_PAYMENTS_REQUEST = 'SML_LEASE_PAYMENTS_REQUEST'
export const SML_LEASE_PAYMENTS_SUCCESS = 'SML_LEASE_PAYMENTS_SUCCESS'
export const SML_LEASE_PAYMENTS_FAIL = 'SML_LEASE_PAYMENTS_FAIL'
export const SML_LEASE_PAYMENTS_RESET = 'SML_LEASE_PAYMENTS_RESET'
